http:
  routers:
    novalup:
      rule: Host(`cpanel.novaluptech.com`)
      entryPoints:
        - websecure
      service: novalup
      tls:
        certResolver: letsencrypt
  services:
    novalup:
      loadBalancer:
        servers:
          - url: http://127.0.0.1:3010
